//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casa
    {
        public int IdCasa { get; set; }
        public int IdArea { get; set; }
        public int IdResidente { get; set; }
        public int NumeroDeHabitantes { get; set; }
        public string Telefono { get; set; }
        public string Descripcion { get; set; }
        public string Letra { get; set; }
        public string Estado { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Residente Residente { get; set; }
    }
}
