//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionRecurso
    {
        public int IdProgramacionRecurso { get; set; }
        public int IdRecurso { get; set; }
        public int IdProgramacion { get; set; }
    
        public virtual ProgramacionVigilancia ProgramacionVigilancia { get; set; }
        public virtual Recurso Recurso { get; set; }
    }
}
