//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residente
    {
        public Residente()
        {
            this.Casa = new HashSet<Casa>();
            this.Factura = new HashSet<Factura>();
            this.Vigilancia = new HashSet<Vigilancia>();
        }
    
        public int IdResidente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int Edad { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Estado { get; set; }
        public string Cedula { get; set; }
    
        public virtual ICollection<Casa> Casa { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual ICollection<Vigilancia> Vigilancia { get; set; }
    }
}
