//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vigilancia
    {
        public int IdVigilancia { get; set; }
        public string Tipo { get; set; }
        public decimal Cuota { get; set; }
        public int IdResidente { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Residente Residente { get; set; }
    }
}
