//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using Entities.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISGIV_Entities : DbContext
    {
        public SISGIV_Entities()
            : base("name=SISGIV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<Avisos_Pago> Avisos_Pago { get; set; }
        public DbSet<Casa> Casa { get; set; }
        public DbSet<Factura> Factura { get; set; }
        public DbSet<ProgramacionRecurso> ProgramacionRecurso { get; set; }
        public DbSet<ProgramacionVigilancia> ProgramacionVigilancia { get; set; }
        public DbSet<Recurso> Recurso { get; set; }
        public DbSet<Residente> Residente { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vigilancia> Vigilancia { get; set; }
        public DbSet<Vigilante> Vigilante { get; set; }
    }
}
